# Generated by Django 5.2.8 on 2025-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerpaymentmethod',
            old_name='account_holder_name',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='freelancerpaymentmethod',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='freelancerpaymentmethod',
            name='created_at',
        ),
        migrations.AddField(
            model_name='freelancerbasicinfo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerpaymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancerpaymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='freelancersociallinks',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancersociallinks',
            name='ratings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='freelancerpaymentmethod',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerpaymentmethod',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancerpaymentmethod',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
