# Generated by Django 5.2.8 on 2025-11-30 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_full_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_location', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_skills', models.JSONField(blank=True, default=list)),
                ('candidate_bio', models.TextField(blank=True, null=True)),
                ('candidate_resume_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed by Recruiter'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Candidate')], default='applied', max_length=32)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['internship'], name='application_interns_98e9af_idx'), models.Index(fields=['candidate'], name='application_candida_a7da83_idx'), models.Index(fields=['status'], name='application_status_850968_idx')],
                'unique_together': {('internship', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_full_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_location', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_skills', models.JSONField(blank=True, default=list)),
                ('candidate_bio', models.TextField(blank=True, null=True)),
                ('candidate_resume_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed by Recruiter'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Candidate')], default='applied', max_length=32)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='application_job_id_6d74c5_idx'), models.Index(fields=['candidate'], name='application_candida_670028_idx'), models.Index(fields=['status'], name='application_status_e72231_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
